name: Update positions

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 12 */1 * 1-5' # Todos os dias, às 12h de segunda a sexta

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          cli: 1.10.2.774

      - name: Scrap positions
        run: clojure -X clojure-empregos-brasil.scraping/-main

      - name: Commit and push
        run: |
          git config --global user.email "renatoalencar.73@gmail.com"
          git config --global user.name "Renato Alencar"
          git commit -am 'Update positions'
          git push origin main
